version: '3.8'

services:
  db:
    image: postgres:15  # Use the desired version of PostgreSQL
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: postgres_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data  # Use a named volume for data persistence

volumes:
  pgdata:
