import { sql, eq } from "drizzle-orm";
import { CreatedWeekly, Weekly } from "~/schemas/reports/weekly";
import { db } from "~/utilties/connection.server";
import {
    buildingTable,
    roomConditionItemsTable,
    staffTable,
    weeklyReportTable,
    residentTable,
    zoneTable,
} from "~/utilties/schema.server";

type Values = { [key: string]: any };

export async function readColonialRCIReports() {
    const data = await db.client.select({
        roomID: residentTable.id,
        emergencyItems: roomConditionItemsTable.emergencyItems,
        walls: roomConditionItemsTable.walls,
        floor: roomConditionItemsTable.floor,
        doorsLocks: roomConditionItemsTable.doorsLocks,
        ceiling: roomConditionItemsTable.ceiling,
        lightsFixtures: roomConditionItemsTable.lightsFixtures,
        closetWardrobeMirror: roomConditionItemsTable.closetWardrobeMirror,
        windowsScreens: roomConditionItemsTable.windowsScreens,
        curtainsRods: roomConditionItemsTable.curtainsRods,
        deskChair: roomConditionItemsTable.deskChair,
        bedMattress: roomConditionItemsTable.bedMattress,
        dresser: roomConditionItemsTable.dresser,
        bathroom: roomConditionItemsTable.bathroom,
        towelbarRings: roomConditionItemsTable.towelbarRings,
        studentSignature: roomConditionItemsTable.studentSignature,
        RASignature: roomConditionItemsTable.RASignature,
        studentDate: roomConditionItemsTable.studentDate,
        RADate: roomConditionItemsTable.RADate,
        entryDoor: roomConditionItemsTable.entryDoor,
        sinkDisposal: roomConditionItemsTable.sinkDisposal,
        countertops: roomConditionItemsTable.countertops,
        dishwasher: roomConditionItemsTable.dishwasher,
        washerDryer: roomConditionItemsTable.washerDryer,
        refrigerator: roomConditionItemsTable.refrigerator,
        stoveOven: roomConditionItemsTable.stoveOven,
        wallCabinets: roomConditionItemsTable.wallCabinets,
        table: roomConditionItemsTable.table,
        chairs: roomConditionItemsTable.chairs,
        fireExtinguisher: roomConditionItemsTable.fireExtinguisher,
        livingRoomCeiling: roomConditionItemsTable.livingRoomCeiling,
        livingRoomFloorCarpet: roomConditionItemsTable.livingRoomFloorCarpet,
        livingRoomWalls: roomConditionItemsTable.livingRoomWalls,
        sofa: roomConditionItemsTable.sofa,
        chair: roomConditionItemsTable.chair,
        sideTable: roomConditionItemsTable.sideTable,
        tvStand: roomConditionItemsTable.tvStand,
        windowBlinds: roomConditionItemsTable.windowBlinds,
        bathroomEntryDoor: roomConditionItemsTable.bathroomEntryDoor,
        bathroomCeiling: roomConditionItemsTable.bathroomCeiling,
        bathroomFloor: roomConditionItemsTable.bathroomFloor,
        bathroomWalls: roomConditionItemsTable.bathroomWalls,
        bathroomCabinets: roomConditionItemsTable.bathroomCabinets,
        bathroomMirror: roomConditionItemsTable.bathroomMirror,
        sinkCounter: roomConditionItemsTable.sinkCounter,
        tubShowerCurtain: roomConditionItemsTable.tubShowerCurtain,
        toilet: roomConditionItemsTable.toilet,
        bedroomLeftEntryDoor: roomConditionItemsTable.bedroomLeftEntryDoor,
        bedroomLeftCeiling: roomConditionItemsTable.bedroomLeftCeiling,
        bedroomLeftFloorCarpet: roomConditionItemsTable.bedroomLeftFloorCarpet,
        bedroomLeftWalls: roomConditionItemsTable.bedroomLeftWalls,
        bedroomLeftBedMattress: roomConditionItemsTable.bedroomLeftBedMattress,
        bedroomLeftClosetMirror: roomConditionItemsTable.bedroomLeftClosetMirror,
        bedroomLeftDeskChair: roomConditionItemsTable.bedroomLeftDeskChair,
        bedroomLeftDresser: roomConditionItemsTable.bedroomLeftDresser,
        bedroomRightEntryDoor: roomConditionItemsTable.bedroomRightEntryDoor,
        bedroomRightCeiling: roomConditionItemsTable.bedroomRightCeiling,
        bedroomRightFloorCarpet: roomConditionItemsTable.bedroomRightFloorCarpet,
        bedroomRightWalls: roomConditionItemsTable.bedroomRightWalls,
        bedroomRightBedMattress: roomConditionItemsTable.bedroomRightBedMattress,
        bedroomRightClosetMirror: roomConditionItemsTable.bedroomRightClosetMirror,
        bedroomRightDeskChair: roomConditionItemsTable.bedroomRightDeskChair,
        bedroomRightDresser: roomConditionItemsTable.bedroomRightDresser,
    });
}