import { count, table } from "node:console";
import { renderToPipeableStream } from "react-dom/server";
import { z } from "zod";

export const URCI = z.object({
  doorsLocks: z.string(),
  emergencyItems: z.string(),
  walls: z.string(),
  floor: z.string(),
  ceiling: z.string(),
  lightsFixtures: z.string(),
  closetWardrobeMirror: z.string(),
  windowsScreens: z.string(),
  curtainsRods: z.string(),
  deskChair: z.string(),
  bedMattress: z.string(),
  dresser: z.string(),
  bathroom: z.string(),
  towelbarRings: z.string(),
});

export const LRCIDouble = z.object({
  foyerKitchenDiningEntryDoor: z.string(),
  foyerKitchenDiningCeiling: z.string(),
  foyerKitchenDiningFloor: z.string(),
  foyerKitchenDiningWalls: z.string(),
  foyerKitchenDiningSinkDisposal: z.string(),
  foyerKitchenDiningCountertops: z.string(),
  foyerKitchenDiningDishwasher: z.string(),
  foyerKitchenDiningWasherDryer: z.string(),
  foyerKitchenDiningRefrigerator: z.string(),
  foyerKitchenDiningStoveOven: z.string(),
  foyerKitchenDiningWallCabinets: z.string(),
  foyerKitchenDiningTable: z.string(),
  foyerKitchenDiningChairs: z.string(),
  foyerKitchenDiningFireExtinguisher: z.string(),
  livingRoomCeiling: z.string(),
  livingRoomFloorCarpet: z.string(),
  livingRoomWalls: z.string(),
  livingRoomSofa: z.string(),
  livingRoomChair: z.string(),
  livingRoomSideTable: z.string(),
  livingRoomTVStand: z.string(),
  livingRoomWindowBlinds: z.string(),
  bathroomEntryDoor: z.string(),
  bathroomCeiling: z.string(),
  bathroomFloor: z.string(),
  bathroomWalls: z.string(),
  bathroomCabinet: z.string(),
  bathroomMirror: z.string(),
  bathroomSinkCounter: z.string(),
  bathroomTubShowerCurtain: z.string(),
  bathroomToilet: z.string(),
  bedroomLeftEntryDoor: z.string(),
  bedroomLeftCeiling: z.string(),
  bedroomLeftFloorCarpet: z.string(),
  bedroomLeftWalls: z.string(),
  bedroomLeftBedMattress: z.string(),
  bedroomLeftClosetMirror: z.string(),
  bedroomLeftDeskChair: z.string(),
  bedroomLeftDresser: z.string(),
  bedroomRightEntryDoor: z.string(),
  bedroomRightCeiling: z.string(),
  bedroomRightFloorCarpet: z.string(),
  bedroomRightWalls: z.string(),
  bedroomRightBedMattress: z.string(),
  bedroomRightClosetMirror: z.string(),
  bedroomRightDeskChair: z.string(),
  bedroomRightDresser: z.string(),
});

export const LRCIQuad = z.object({
  kitchenFloor: z.string(),
  kitchenStoveOven: z.string(),
  kitchenCountertops: z.string(),
  kitchenCabinets: z.string(),
  kitchenRefrigerator: z.string(),
  kitchenWasherDryer: z.string(),
  kitchenDishwasher: z.string(),
  kitchenWallsCeiling: z.string(),
  kitchenSinkDisposal: z.string(),
  kitchenFireExtinguisher: z.string(),
  kitchenTable: z.string(),
  kitchenChairs: z.string(),
  livingRoomFloor: z.string(),
  livingRoomWallsCeiling: z.string(),
  livingRoomSofa: z.string(),
  livingRoomChair: z.string(),
  livingRoomSideTable: z.string(),
  livingRoomTVStand: z.string(),
  livingRoomWindowsBlinds: z.string(),
  bathroomABHallwayWallsFloor: z.string(),
  bathroomABEntryDoor: z.string(),
  bathroomABFloor: z.string(),
  bathroomABWallsCeiling: z.string(),
  bathroomABSinkCounter: z.string(),
  bathroomABMirror: z.string(),
  bathroomABCabinets: z.string(),
  bathroomABShowerCurtainRings: z.string(),
  bathroomABToilet: z.string(),
  bathroomCDHallwayWallsFloor: z.string(),
  bathroomCDEntryDoor: z.string(),
  bathroomCDFloor: z.string(),
  bathroomCDWallsCeiling: z.string(),
  bathroomCDSinkCounter: z.string(),
  bathroomCDMirror: z.string(),
  bathroomCDCabinets: z.string(),
  bathroomCDShowerCurtainRings: z.string(),
  bathroomCDToilet: z.string(),
  bedroomAEntryDoor: z.string(),
  bedroomAFloor: z.string(),
  bedroomAWallsCeiling: z.string(),
  bedroomAClosetMirror: z.string(),
  bedroomABedMattress: z.string(),
  bedroomADeskChair: z.string(),
  bedroomADresser: z.string(),
  bedroomBEntryDoor: z.string(),
  bedroomBFloor: z.string(),
  bedroomBWallsCeiling: z.string(),
  bedroomBClosetMirror: z.string(),
  bedroomBBedMattress: z.string(),
  bedroomBDeskChair: z.string(),
  bedroomBDresser: z.string(),
  bedroomCEntryDoor: z.string(),
  bedroomCFloor: z.string(),
  bedroomCWallsCeiling: z.string(),
  bedroomCClosetMirror: z.string(),
  bedroomCBedMattress: z.string(),
  bedroomCDeskChair: z.string(),
  bedroomCDresser: z.string(),
  bedroomDEntryDoor: z.string(),
  bedroomDFloor: z.string(),
  bedroomDWallsCeiling: z.string(),
  bedroomDClosetMirror: z.string(),
  bedroomDBedMattress: z.string(),
  bedroomDDeskChair: z.string(),
  bedroomDDresser: z.string(),
});

export const CreatedURCI = URCI.extend({
  id: z.undefined(),
});
