export const upperCampusMapping = {
  doorsLocks: "Doors Locks",
  emergencyItems: "Emergency Items",
  walls: "Walls",
  floor: "Floor",
  ceiling: "Ceiling",
  lightFixtures: "Light Fixtures",
  closetWardrobeMirror: "Closet",
  windowScreens: "Window Screens",
  curtainsRods: "Curtain Rods",
  deskChair: "Desk Chair",
  bedMattress: "Bed Mattress",
  dresser: "Dresser",
  bathroom: "Bathroom",
  towelbarRings: "Towel Bar Rings",
};

export const colonialQuadMapping = {
  kitchenFloor: "Kitchen Floor",
  kitchenStoveOven: "Kitchen Stove Oven",
  kitchenCountertops: "Kitchen Countertops",
  kitchenCabinets: "Kitchen Cabinets",
  kitchenRefrigerator: "Kitchen Refrigerator",
  kitchenWasherDryer: "Kitchen Washer Dryer",
  kitchenDishwasher: "Kitchen Dishwasher",
  kitchenWallsCeiling: "Kitchen Walls Ceiling",
  kitchenSinkDisposal: "Kitchen Sink Disposal",
  kitchenFireExtinguisher: "Kitchen Fire Extinguisher",
  kitchenTable: "Kitchen Table",
  kitchenChairs: "Kitchen Chairs",
  livingRoomFloor: "Living Room Floor",
  livingRoomWallsCeiling: "Living Room Walls Ceiling",
  livingRoomSofa: "Living Room Sofa",
  livingRoomChair: "Living Room Chair",
  livingRoomSideTable: "Living Room Side Table",
  livingRoomTVStand: "Living Room TV Stand",
  livingRoomWindowsBlinds: "Living Room Windows Blinds",
  bathroomABHallwayWallsFloor: "Bathroom AB Hallway Walls Floor",
  bathroomABEntryDoor: "Bathroom AB Entry Door",
  bathroomABFloor: "Bathroom AB Floor",
  bathroomABWallsCeiling: "Bathroom AB Walls Ceiling",
  bathroomABSinkCounter: "Bathroom AB Sink Counter",
  bathroomABMirror: "Bathroom AB Mirror",
  bathroomABCabinets: "Bathroom AB Cabinets",
  bathroomABShowerCurtainRings: "Bathroom AB Shower Curtain Rings",
  bathroomABToilet: "Bathroom AB Toilet",
  bathroomCDHallwayWallsFloor: "Bathroom CD Hallway Walls Floor",
  bathroomCDEntryDoor: "Bathroom CD Entry Door",
  bathroomCDFloor: "Bathroom CD Floor",
  bathroomCDWallsCeiling: "Bathroom CD Walls Ceiling",
  bathroomCDSinkCounter: "Bathroom CD Sink Counter",
  bathroomCDMirror: "Bathroom CD Mirror",
  bathroomCDCabinets: "Bathroom CD Cabinets",
  bathroomCDShowerCurtainRings: "Bathroom CD Shower Curtain Rings",
  bathroomCDToilet: "Bathroom CD Toilet",
  bedroomAEntryDoor: "Bedroom A Entry Door",
  bedroomAFloor: "Bedroom A Floor",
  bedroomAWallsCeiling: "Bedroom A Walls Ceiling",
  bedroomAClosetMirror: "Bedroom A Closet Mirror",
  bedroomABedMattress: "Bedroom A Bed Mattress",
  bedroomADeskChair: "Bedroom A Desk Chair",
  bedroomADresser: "Bedroom A Dresser",
  bedroomBEntryDoor: "Bedroom B Entry Door",
  bedroomBFloor: "Bedroom B Floor",
  bedroomBWallsCeiling: "Bedroom B Walls Ceiling",
  bedroomBClosetMirror: "Bedroom B Closet Mirror",
  bedroomBBedMattress: "Bedroom B Bed Mattress",
  bedroomBDeskChair: "Bedroom B Desk Chair",
  bedroomBDresser: "Bedroom B Dresser",
  bedroomCEntryDoor: "Bedroom C Entry Door",
  bedroomCFloor: "Bedroom C Floor",
  bedroomCWallsCeiling: "Bedroom C Walls Ceiling",
  bedroomCClosetMirror: "Bedroom C Closet Mirror",
  bedroomCBedMattress: "Bedroom C Bed Mattress",
  bedroomCDeskChair: "Bedroom C Desk Chair",
  bedroomCDresser: "Bedroom C Dresser",
  bedroomDEntryDoor: "Bedroom D Entry Door",
  bedroomDFloor: "Bedroom D Floor",
  bedroomDWallsCeiling: "Bedroom D Walls Ceiling",
  bedroomDClosetMirror: "Bedroom D Closet Mirror",
  bedroomDBedMattress: "Bedroom D Bed Mattress",
  bedroomDDeskChair: "Bedroom D Desk Chair",
  bedroomDDresser: "Bedroom D Dresser",
};

export const colonialDoubleMapping = {
  foyerKitchenDiningEntryDoor: "Foyer Kitchen Dining Entry Door",
  foyerKitchenDiningCeiling: "Foyer Kitchen Dining Ceiling",
  foyerKitchenDiningFloor: "Foyer Kitchen Dining Floor",
  foyerKitchenDiningWalls: "Foyer Kitchen Dining Walls",
  foyerKitchenDiningSinkDisposal: "Foyer Kitchen Dining Sink Disposal",
  foyerKitchenDiningCountertops: "Foyer Kitchen Dining Countertops",
  foyerKitchenDiningDishwasher: "Foyer Kitchen Dining Dishwasher",
  foyerKitchenDiningWasherDryer: "Foyer Kitchen Dining Washer Dryer",
  foyerKitchenDiningRefrigerator: "Foyer Kitchen Dining Refrigerator",
  foyerKitchenDiningStoveOven: "Foyer Kitchen Dining Stove Oven",
  foyerKitchenDiningWallCabinets: "Foyer Kitchen Dining Wall Cabinets",
  foyerKitchenDiningTable: "Foyer Kitchen Dining Table",
  foyerKitchenDiningChairs: "Foyer Kitchen Dining Chairs",
  foyerKitchenDiningFireExtinguisher: "Foyer Kitchen Dining Fire Extinguisher",
  livingRoomCeiling: "Living Room Ceiling",
  livingRoomFloorCarpet: "Living Room Floor Carpet",
  livingRoomWalls: "Living Room Walls",
  livingRoomSofa: "Living Room Sofa",
  livingRoomChair: "Living Room Chair",
  livingRoomSideTable: "Living Room Side Table",
  livingRoomTVStand: "Living Room TV Stand",
  livingRoomWindowBlinds: "Living Room Window Blinds",
  bathroomEntryDoor: "Bathroom Entry Door",
  bathroomCeiling: "Bathroom Ceiling",
  bathroomFloor: "Bathroom Floor",
  bathroomWalls: "Bathroom Walls",
  bathroomCabinet: "Bathroom Cabinet",
  bathroomMirror: "Bathroom Mirror",
  bathroomSinkCounter: "Bathroom Sink Counter",
  bathroomTubShowerCurtain: "Bathroom Tub Shower Curtain",
  bathroomToilet: "Bathroom Toilet",
  bedroomLeftEntryDoor: "Bedroom Left Entry Door",
  bedroomLeftCeiling: "Bedroom Left Ceiling",
  bedroomLeftFloorCarpet: "Bedroom Left Floor Carpet",
  bedroomLeftWalls: "Bedroom Left Walls",
  bedroomLeftBedMattress: "Bedroom Left Bed Mattress",
  bedroomLeftClosetMirror: "Bedroom Left Closet Mirror",
  bedroomLeftDeskChair: "Bedroom Left Desk Chair",
  bedroomLeftDresser: "Bedroom Left Dresser",
  bedroomRightEntryDoor: "Bedroom Right Entry Door",
  bedroomRightCeiling: "Bedroom Right Ceiling",
  bedroomRightFloorCarpet: "Bedroom Right Floor Carpet",
  bedroomRightWalls: "Bedroom Right Walls",
  bedroomRightBedMattress: "Bedroom Right Bed Mattress",
  bedroomRightClosetMirror: "Bedroom Right Closet Mirror",
  bedroomRightDeskChair: "Bedroom Right Desk Chair",
  bedroomRightDresser: "Bedroom Right Dresser",
};
