import { z } from "zod";

export const ColonialQuadIssues = z.object({
  kitchenFloor: z.string(),
  kitchenStoveOven: z.string(),
  kitchenCountertops: z.string(),
  kitchenCabinets: z.string(),
  kitchenRefrigerator: z.string(),
  kitchenWasherDryer: z.string(),
  kitchenDishwasher: z.string(),
  kitchenWallsCeiling: z.string(),
  kitchenSinkDisposal: z.string(),
  kitchenFireExtinguisher: z.string(),
  kitchenTable: z.string(),
  kitchenChairs: z.string(),
  livingRoomFloor: z.string(),
  livingRoomWallsCeiling: z.string(),
  livingRoomSofa: z.string(),
  livingRoomChair: z.string(),
  livingRoomSideTable: z.string(),
  livingRoomTVStand: z.string(),
  livingRoomWindowsBlinds: z.string(),
  bathroomABHallwayWallsFloor: z.string(),
  bathroomABEntryDoor: z.string(),
  bathroomABFloor: z.string(),
  bathroomABWallsCeiling: z.string(),
  bathroomABSinkCounter: z.string(),
  bathroomABMirror: z.string(),
  bathroomABCabinets: z.string(),
  bathroomABShowerCurtainRings: z.string(),
  bathroomABToilet: z.string(),
  bathroomCDHallwayWallsFloor: z.string(),
  bathroomCDEntryDoor: z.string(),
  bathroomCDFloor: z.string(),
  bathroomCDWallsCeiling: z.string(),
  bathroomCDSinkCounter: z.string(),
  bathroomCDMirror: z.string(),
  bathroomCDCabinets: z.string(),
  bathroomCDShowerCurtainRings: z.string(),
  bathroomCDToilet: z.string(),
  bedroomAEntryDoor: z.string(),
  bedroomAFloor: z.string(),
  bedroomAWallsCeiling: z.string(),
  bedroomAClosetMirror: z.string(),
  bedroomABedMattress: z.string(),
  bedroomADeskChair: z.string(),
  bedroomADresser: z.string(),
  bedroomBEntryDoor: z.string(),
  bedroomBFloor: z.string(),
  bedroomBWallsCeiling: z.string(),
  bedroomBClosetMirror: z.string(),
  bedroomBBedMattress: z.string(),
  bedroomBDeskChair: z.string(),
  bedroomBDresser: z.string(),
  bedroomCEntryDoor: z.string(),
  bedroomCFloor: z.string(),
  bedroomCWallsCeiling: z.string(),
  bedroomCClosetMirror: z.string(),
  bedroomCBedMattress: z.string(),
  bedroomCDeskChair: z.string(),
  bedroomCDresser: z.string(),
  bedroomDEntryDoor: z.string(),
  bedroomDFloor: z.string(),
  bedroomDWallsCeiling: z.string(),
  bedroomDClosetMirror: z.string(),
  bedroomDBedMattress: z.string(),
  bedroomDDeskChair: z.string(),
  bedroomDDresser: z.string(),
});

export const CreatedColonialQuad = ColonialQuadIssues.extend({
  roomId: z.coerce.number(),
  studentSignature: z.string(),
});
