import { z } from "zod";

export const ColonialDoubleIssues = z.object({
  foyerKitchenDiningEntryDoor: z.string(),
  foyerKitchenDiningCeiling: z.string(),
  foyerKitchenDiningFloor: z.string(),
  foyerKitchenDiningWalls: z.string(),
  foyerKitchenDiningSinkDisposal: z.string(),
  foyerKitchenDiningCountertops: z.string(),
  foyerKitchenDiningDishwasher: z.string(),
  foyerKitchenDiningWasherDryer: z.string(),
  foyerKitchenDiningRefrigerator: z.string(),
  foyerKitchenDiningStoveOven: z.string(),
  foyerKitchenDiningWallCabinets: z.string(),
  foyerKitchenDiningTable: z.string(),
  foyerKitchenDiningChairs: z.string(),
  foyerKitchenDiningFireExtinguisher: z.string(),
  livingRoomCeiling: z.string(),
  livingRoomFloorCarpet: z.string(),
  livingRoomWalls: z.string(),
  livingRoomSofa: z.string(),
  livingRoomChair: z.string(),
  livingRoomSideTable: z.string(),
  livingRoomTVStand: z.string(),
  livingRoomWindowBlinds: z.string(),
  bathroomEntryDoor: z.string(),
  bathroomCeiling: z.string(),
  bathroomFloor: z.string(),
  bathroomWalls: z.string(),
  bathroomCabinet: z.string(),
  bathroomMirror: z.string(),
  bathroomSinkCounter: z.string(),
  bathroomTubShowerCurtain: z.string(),
  bathroomToilet: z.string(),
  bedroomLeftEntryDoor: z.string(),
  bedroomLeftCeiling: z.string(),
  bedroomLeftFloorCarpet: z.string(),
  bedroomLeftWalls: z.string(),
  bedroomLeftBedMattress: z.string(),
  bedroomLeftClosetMirror: z.string(),
  bedroomLeftDeskChair: z.string(),
  bedroomLeftDresser: z.string(),
  bedroomRightEntryDoor: z.string(),
  bedroomRightCeiling: z.string(),
  bedroomRightFloorCarpet: z.string(),
  bedroomRightWalls: z.string(),
  bedroomRightBedMattress: z.string(),
  bedroomRightClosetMirror: z.string(),
  bedroomRightDeskChair: z.string(),
  bedroomRightDresser: z.string(),
});

export const CreatedColonialDouble = ColonialDoubleIssues.extend({
  roomId: z.coerce.number(),
  studentSignature: z.string(),
});
