import { z } from "zod";

export const ColonialQuadIssues = z.object({
  kitchenFloor: z.string().optional(),
  kitchenStoveOven: z.string().optional(),
  kitchenCountertops: z.string().optional(),
  kitchenCabinets: z.string().optional(),
  kitchenRefrigerator: z.string().optional(),
  kitchenWasherDryer: z.string().optional(),
  kitchenDishwasher: z.string().optional(),
  kitchenWallsCeiling: z.string().optional(),
  kitchenSinkDisposal: z.string().optional(),
  kitchenFireExtinguisher: z.string().optional(),
  kitchenTable: z.string().optional(),
  kitchenChairs: z.string().optional(),
  livingRoomFloor: z.string().optional(),
  livingRoomWallsCeiling: z.string().optional(),
  livingRoomSofa: z.string().optional(),
  livingRoomChair: z.string().optional(),
  livingRoomSideTable: z.string().optional(),
  livingRoomTVStand: z.string().optional(),
  livingRoomWindowsBlinds: z.string().optional(),
  bathroomABHallwayWallsFloor: z.string().optional(),
  bathroomABEntryDoor: z.string().optional(),
  bathroomABFloor: z.string().optional(),
  bathroomABWallsCeiling: z.string().optional(),
  bathroomABSinkCounter: z.string().optional(),
  bathroomABMirror: z.string().optional(),
  bathroomABCabinets: z.string().optional(),
  bathroomABShowerCurtainRings: z.string().optional(),
  bathroomABToilet: z.string().optional(),
  bathroomCDHallwayWallsFloor: z.string().optional(),
  bathroomCDEntryDoor: z.string().optional(),
  bathroomCDFloor: z.string().optional(),
  bathroomCDWallsCeiling: z.string().optional(),
  bathroomCDSinkCounter: z.string().optional(),
  bathroomCDMirror: z.string().optional(),
  bathroomCDCabinets: z.string().optional(),
  bathroomCDShowerCurtainRings: z.string().optional(),
  bathroomCDToilet: z.string().optional(),
  bedroomAEntryDoor: z.string().optional(),
  bedroomAFloor: z.string().optional(),
  bedroomAWallsCeiling: z.string().optional(),
  bedroomAClosetMirror: z.string().optional(),
  bedroomABedMattress: z.string().optional(),
  bedroomADeskChair: z.string().optional(),
  bedroomADresser: z.string().optional(),
  bedroomBEntryDoor: z.string().optional(),
  bedroomBFloor: z.string().optional(),
  bedroomBWallsCeiling: z.string().optional(),
  bedroomBClosetMirror: z.string().optional(),
  bedroomBBedMattress: z.string().optional(),
  bedroomBDeskChair: z.string().optional(),
  bedroomBDresser: z.string().optional(),
  bedroomCEntryDoor: z.string().optional(),
  bedroomCFloor: z.string().optional(),
  bedroomCWallsCeiling: z.string().optional(),
  bedroomCClosetMirror: z.string().optional(),
  bedroomCBedMattress: z.string().optional(),
  bedroomCDeskChair: z.string().optional(),
  bedroomCDresser: z.string().optional(),
  bedroomDEntryDoor: z.string().optional(),
  bedroomDFloor: z.string().optional(),
  bedroomDWallsCeiling: z.string().optional(),
  bedroomDClosetMirror: z.string().optional(),
  bedroomDBedMattress: z.string().optional(),
  bedroomDDeskChair: z.string().optional(),
  bedroomDDresser: z.string().optional(),
});

export const CreatedColonialQuad = ColonialQuadIssues.extend({
  studentSignature: z.string(),
});
